name: jtn
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  dotted_line: ^3.2.2
  # intl: ^0.19.0
  intl: 0.18.1
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  get_storage: ^2.1.1
  fluttertoast: ^8.2.4
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  dropdown_button2: ^2.3.9
  image_picker: ^1.0.5
  permission_handler: ^11.1.0
  flutter_image_compress: ^2.1.0
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^16.2.0
  # fluttertoast: ^8.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/
